### PR TITLE
Updated Makefile

### PR DESCRIPTION
**Pull request by j-koreth**
Updated the Makefile build look for and build using the Haiku makefile-engine

### CODE REVIEW

**Comment by scottmc** [comment]
What's the license for this program?  When importing to HaikuArchives that is one question that needs to be asked of the authors if it isn't already apparent from looking at the code.

**Comment by j-koreth** [comment]
This program is a port of GTKTILink to BeOS and GTKTiLink is a GPL2 licensed program so should I just add that license? I can't seem to find any information to contact the original authors.

**Comment by scottmc** [comment]
Maybe @waddlesplash can shed some light on where it came from and who the orig author of the port was?

**Comment by waddlesplash** [comment]
It's from here: http://www.ticalc.org/archives/files/fileinfo/139/13943.html

**Comment by scottmc** [comment]
AMain_Window.cpp provides the answer, go with GNU GPL v2

**Comment by j-koreth** [comment]
Added the license, anything else?

**Comment by scottmc** [comment]
How about adding a readme.md with a screenshot?  Set screenshot to capture current window, see https://www.haiku-os.org/docs/userguide/en/applications/screenshot.html

**Comment by j-koreth** [comment]
Created the readme.md and added the screenshot

**Pull request merged**
